name: Publish Galera Cluster Healthcheck to GHCR


permissions:
  contents: read
  packages: write


on:
  push:
     tags: 
      - 'v*.*.*'
      - 'v*.*.*-dev.*'


jobs: 
    semgrep_scan:
        name: Smegrep Scan Analysis
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.x
        
        - name: Install semgrep
          run: python3 -m pip install semgrep
        
        - name: Run semgrep
          run:  semgrep scan --error

    
    build:
      name: Build Docker image
      needs: semgrep_scan
      strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-24.04
            - ubuntu-24.04-arm
      runs-on: ${{ matrix.os }}
      steps:
        - name: Extract Git info
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            platform=${{ matrix.os == 'ubuntu-24.04' && 'linux/amd64' || 'linux/arm64' }}
            arch=${{ matrix.os == 'ubuntu-24.04' && 'amd64' || 'arm64' }}
            echo "ARCH=${arch}" >> $GITHUB_ENV
            echo "PLATFORM=${platform}" >> $GITHUB_ENV
            echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

        - uses: actions/checkout@v4

        - name: Set up Qemu 
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GHCR 
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ env.REPOSITORY_NAME }}
            labels: |
              org.opencontainers.image.title=Galera Cluster Healthcheck
              org.opencontainers.image.description=A simple and efficient healthchecker for Galera Clusters
              org.opencontainers.image.authors=SeaweedbrainCY <contact@seaweedbrain.xyz>
              org.opencontainers.image.url=https://github.com/seaweedbraincy/galera_cluster_healthcheck
              maintainer=SeaweedbrainCY <contact@seaweedbrain.xyz>
            annotations: |
              org.opencontainers.image.description=A simple and efficient healthchecker for Galera Clusters
              org.opencontainers.image.source=https://github.com/seaweedbraincy/galera_cluster_healthcheck

            
        
        - name: Build Docker image
          uses: docker/build-push-action@v5
          id: build
          with:
            context: .
            file: ./Dockerfile
            labels: ${{ steps.meta.outputs.labels }}
            annotations: ${{ steps.meta.outputs.annotations }}
            build-args: |
              VERSION=${{ github.ref_name }}
            cache-from: type=gha
            tags: ghcr.io/${{ env.REPOSITORY_NAME }}
            cache-to: type=gha,mode=max
            platforms:  ${{ env.PLATFORM }}
            outputs: type=image,push-by-digest=true,name-canonical=true,push=true

        - name: Export digest
          run: |
            mkdir -p ${{ runner.temp }}/digests
            digest="${{ steps.build.outputs.digest }}"
            touch "${{ runner.temp }}/digests/${digest#sha256:}"

        - name: Upload digest
          uses: actions/upload-artifact@v4
          with:
            name: digests-${{ env.PLATFORM_PAIR }}
            path: ${{ runner.temp }}/digests/*
            if-no-files-found: error
            retention-days: 1

    merge-manifests:
      name: Merge manifests and publish multi-arch image
      runs-on: ubuntu-latest
      needs:
        - build
      steps:
        - name: Extract Git commit
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            echo "CURRENT_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')"  >> $GITHUB_ENV

        - name: Download digests
          uses: actions/download-artifact@v4
          with:
            path: ${{ runner.temp }}/digests
            pattern: digests-*
            merge-multiple: true

        - name: Login to GHCR 
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3


        - name: Generate docker metadata 
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ env.REPOSITORY_NAME }}
            tags: |
              type=semver,pattern={{version}}
            annotations: |
              org.opencontainers.image.description=A simple and efficient healthchecker for Galera Clusters
              org.opencontainers.image.source=https://github.com/seaweedbraincy/galera_cluster_healthcheck


        - name: Create manifest list and push
          working-directory: ${{ runner.temp }}/digests
          run: |
            docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<<   "$DOCKER_METADATA_OUTPUT_JSON") \
              $(printf 'ghcr.io/${{ env.REPOSITORY_NAME }}@sha256:%s ' *) 

        - name: Inspect image
          run: |
            docker buildx imagetools inspect ghcr.io/${{ env.REPOSITORY_NAME }}:${{ steps.meta.outputs.version }}

    trivy_scan:
      name: Trivy Security Scan of the built image
      needs: merge-manifests
      runs-on: ubuntu-latest
      steps:
        - name: Extract Git info
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            platform=${{ matrix.os == 'ubuntu-24.04' && 'linux/amd64' || 'linux/arm64' }}
            arch=${{ matrix.os == 'ubuntu-24.04' && 'amd64' || 'arm64' }}
            echo "VERSION"=$(echo ${{ github.ref_name }} | sed 's/^v//')  >> $GITHUB_ENV 

        - uses: actions/checkout@v3
        - name: Install Trivy
          run: |
            sudo apt-get install wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy

        - name: Scan Docker image
          run: |
            trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress --ignore-unfixed ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }}

    tag_image_as_latest:
      name: Tag Docker image as latest
      needs: trivy_scan
      runs-on: ubuntu-latest
      if: contains( github.ref_name, 'dev') == false
      steps:
        - name: Extract Git info
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            echo "VERSION"=$(echo ${{ github.ref_name }} | sed 's/^v//')  >> $GITHUB_ENV 
            
        - name: Login to GHCR 
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Tag and push latest image
          run: docker buildx imagetools create -t ghcr.io/${{ env.REPOSITORY_NAME }}:latest ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }}
            
    tag_image_as_dev:
      name: Tag Docker image as  dev
      needs: trivy_scan
      runs-on: ubuntu-latest
      if: contains( github.ref_name, 'dev')
      steps:
        - name: Extract Git info
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            echo "VERSION"=$(echo ${{ github.ref_name }} | sed 's/^v//')  >> $GITHUB_ENV 
            
        - name: Login to GHCR 
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Tag and push latest image
          run:  docker buildx imagetools create -t ghcr.io/${{ env.REPOSITORY_NAME }}:dev ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.VERSION }}